### ISSUE TITLE
Python 3.5 issues with imports

### ISSUE THREAD

**Issue by nickbreen** [pberkes/big_O#14]
Failing example available: https://github.com/nickbreen/big_o_test

When trying this in a trivial Python 3.5 virtual environment there are errors.

`pytest.py` (abridged)

```
import big_o

class Test(unittest.TestCase):

    def testPerf(self):
        gen = lambda n: big_o.datagen.large_integers(n)
        best, others = big_o.big_o(solution, gen, n_repeats=100)
        self.assertEqual(big_o.complexities.Linear, best)
```

```
pytest test.py
```

Output:

```
================================================= test session starts =================================================
platform linux -- Python 3.5.2, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: /home/nick/Code/big_o_p35, inifile:
collected 0 items / 1 errors                                                                                          

======================================================= ERRORS ========================================================
______________________________________________ ERROR collecting test.py _______________________________________________
ImportError while importing test module '/home/nick/Code/big_o_p35/test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test.py:2: in <module>
    import big_o
venv/lib/python3.5/site-packages/big_o/__init__.py:6: in <module>
    import datagen
E   ImportError: No module named 'datagen'
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=============================================== 1 error in 0.08 seconds ===============================================
```

**Comment by pberkes** [comment]
Hi @nickbreen , it looks like you are using an old version of the code that is not Python 3 compatible.

You probably downloaded it from PyPI, I need to do a new release.

**Comment by pberkes** [comment]
I just release 0.8 on PyPI, please give it a try and let me know

**Comment by nickbreen** [comment]
Got this error:

```
Collecting big_o (from -r requirements.txt (line 1))
  Downloading big_O-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5mqyphi8/big-o/setup.py", line 4, in <module>
        with open('README.rst') as readme_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5mqyphi8/big-o/
```

**Comment by pberkes** [comment]
My bad sorry 😞 
Should be fixed now

**Comment by nickbreen** [comment]
Thanks!
